### PR TITLE
Update Swift Protobuf to 1.0.0

### PR DESCRIPTION
**Pull request by tengyifei**
JIRA: http://jira.perfect.org:8080/servicedesk/customer/portal/1/ISS-542

### CODE REVIEW

**Comment by RockfordWei** [comment]
TensorFlow 1.4 is coming with a new interface named “function “ . Would you like to wait for it a bit? It is 1.4.0 rc

**Comment by tengyifei** [comment]
Sure. But it doesn't conflict with this PR does it? Everything in
Perfect-Tensorflow is TF1.3 rn

**Comment by RockfordWei** [comment]
Thank you!

**Comment by RockfordWei** [comment]
Would you like to join our slack http://perfect.ly?

**Pull request merged**
